apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible-clickhouse
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible-clickhouse
  template:
    metadata:
      labels:
        app: plausible-clickhouse
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: plausible-clickhouse
          image: clickhouse/clickhouse-server:24.3.3.102-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: plausible-volume
              subPath: clickhouse/data
            - mountPath: /var/log/clickhouse-server
              name: plausible-volume
              subPath: clickhouse/logs
      volumes:
        - name: plausible-volume
          persistentVolumeClaim:
            claimName: plausible-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: plausible-clickhouse
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 8123
  selector:
    app: plausible-clickhouse