apiVersion: v1
kind: Secret
metadata:
  name: plausible-db-secret
  namespace: production
type: Opaque
stringData:
  POSTGRES_DB: plausible_db
  POSTGRES_USER: plausible_db_user
  POSTGRES_PASSWORD: $PLAUSIBLE_DB_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible-db
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible-db
  template:
    metadata:
      labels:
        app: plausible-db
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: plausible-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: plausible-db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: plausible-volume
              subPath: db
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux doesn't play well with K8s PVCs
      volumes:
        - name: plausible-volume
          persistentVolumeClaim:
            claimName: plausible-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: plausible-db
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: plausible-db
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: plausible-db
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: plausible-db
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: plausible
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: plausible