apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
  namespace: production
  labels:
    app: plausible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible
  template:
    metadata:
      labels:
        app: plausible
    spec:
      containers:
        - name: plausible
          image: ghcr.io/plausible/community-edition:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command: ["/bin/sh"]
          args: ["-c", "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"]
          env:
          - name: BASE_URL
            value: "https://plausible.$SERVICES_DOMAIN"
          - name: SECRET_KEY_BASE
            value: "HEJkT3HCVfH9nhWJTB6NPq9faPvWZB69H51JJGQEWGVe2YNuOnoILpH3M+L/Cc8m" # PROD TODO: Replace with prod value
          - name: TOTP_VAULT_KEY
            value: "cwcunViPJi3h5Vz9MXakMo2cmeEkIasIw7dxFwcUpgA=" # PROD TODO: Replace with prod value
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: plausible-db-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: plausible-db-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: plausible-db-secret
                key: POSTGRES_PASSWORD
          - name: DATABASE_URL
            value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@plausible-db.production.svc.cluster.local:5432/$(POSTGRES_DB)
          - name: CLICKHOUSE_DATABASE_URL
            value: http://plausible-clickhouse.production.svc.cluster.local:8123/plausible_events_db
---
apiVersion: v1
kind: Service
metadata:
  name: plausible
  namespace: production
  labels:
    app: plausible
spec:
  selector:
    app: plausible
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP