services:

    strelaysrv:
        image: imranrdev/strelaysrv-docker:latest
        container_name: strelaysrv
        restart: always
        volumes:
            - strelaysrv:/keys
        command:
            - "-global-rate=5000000"
            - "-provided-by=$SERVICES_TOP_DOMAIN"
        ports:
            - 22067:22067
            - 22070:22070

volumes:
    strelaysrv: {}