services:

    # FRPC - Reverse Proxy Client
    frpc:
        image: fatedier/frpc:v0.61.1
        container_name: frpc
        restart: always
        volumes:
        - $STATE_DIR/frpc/frpc.ini:/frpc.ini
        network_mode: host