apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: production
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
        fsGroup: $MY_UID
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: files
              mountPath: /files
            - name: state
              mountPath: /state
            - name: config
              mountPath: /.filebrowser.json
              subPath: filebrowser.json
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux may cause issues with file watching/reading for external libraries
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: home-pvc
        - name: state
          persistentVolumeClaim:
            claimName: filebrowser-pvc
        - name: config
          configMap:
            name: filebrowser-config
            items:
              - key: filebrowser.json
                path: filebrowser.json
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: production
  labels:
    app: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
