---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-pv
  namespace: production
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/imranr/k8s/state/authelia
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: main-storage
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: authelia-pv
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-nfs-cm
  namespace: production
data:
  etab: |
    /data *(rw,sync,wdelay,hide,nocrossmnt,insecure,root_squash,no_all_squash,no_subtree_check,secure_locks,acl,no_pnfs,fsid=0,anonuid=65534,anongid=65534,sec=sys)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia-nfs
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia-nfs
  template:
    metadata:
      labels:
        app: authelia-nfs
    spec:
      initContainers:
        - name: nfs-modules
          image: busybox:1.36.1-uclibc@sha256:97e3873d1f61ba651b632e4755fc52e1d90c9f6e4f01d9b720f37af5efed17e5
          args:
            - "modprobe"
            - "nfs"
            - "nfsd"
          securityContext:
            privileged: true
            capabilities:
              add:
                - "SYS_MODULE"
          volumeMounts:
            - mountPath: /lib/modules
              name: modules
              readOnly: true
      containers:
        - name: nfs-server
          image: ghcr.io/trexx/docker-nfs-server:latest
          ports:
            - name: nfsv4
              containerPort: 2049
              protocol: TCP
          securityContext:
            privileged: true
            capabilities:
              add:
                - "SYS_ADMIN"
          volumeMounts:
            - mountPath: /data
              name: authelia-nfs-data
              readOnly: false
            - name: nfs-exports
              mountPath: /var/lib/nfs/etab
              subPath: etab
              readOnly: true
      volumes:
        - name: modules
          hostPath:
            path: /lib/modules
        - name: nfs-exports
          configMap:
            name: authelia-nfs-cm
        - name: authelia-nfs-data
          persistentVolumeClaim:
            claimName: authelia-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: authelia-nfs
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 2049
  selector:
    app: authelia-nfs
  clusterIP: 10.96.172.221
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authelia-nfs-pv
  namespace: production
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /
    server: 10.96.172.221
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-nfs-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: authelia-nfs
  namespace: production
spec:
  podSelector:
    matchLabels:
      app: authelia-nfs
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: authelia