pod:
  kind: StatefulSet
  extraVolumeMounts:
    - name: users-database
      mountPath: "/config/users"
      readOnly: true
  extraVolumes:
    - name: users-database
      secret:
        secretName: authelia-users
        items:
          - key: users-database.yaml
            path: users-database.yaml
configMap:
  authentication_backend:
    ldap:
      enabled: false
    file:
      enabled: true
      password:
        algorithm: sha512
        iterations: 100000
      path: /config/users/users-database.yaml
  session:
    redis:
      enabled: false
    cookies:
      -
        subdomain: 'auth.staging'
        domain: 'imranr.dev'
        path: ''
        default_redirection_url: ''
  storage:
    local:
      enabled: true
    postgres:
      enabled: false
  notifier:
    filesystem:
      enabled: true
    smtp:
      enabled: false
  identity_providers:
    oidc:
      enabled: false
  log:
    level: debug
  totp:
    issuer: imranr.dev
  access_control:
    rules:
      - domain: '*.imranr.dev'
        policy: one_factor
        subject:
          - 'group:admins'
  regulation:
    max_retries: 3
    find_time: 120
    ban_time: 300