apiVersion: v1
kind: PersistentVolume
metadata:
  name: main-external-media-pv
  namespace: production
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/home/imranr/k8s/mock-data/Main/External Media" # PROD TODO: Replace this with the actual path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: main-storage
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: main-external-media-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4000Gi
  volumeName: main-external-media-pv