---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monerod
  namespace: production
  labels:
    app: monerod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monerod
  template:
    metadata:
      labels:
        app: monerod
    spec:
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
        fsGroup: $MY_UID
      containers:
        - name: monerod
          image: sethsimmons/simple-monerod:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: home
              mountPath: /home/monero/.bitmonero
              subPath: .bitmonero
          args: ["--rpc-restricted-bind-ip=0.0.0.0", "--rpc-restricted-bind-port=18089", "--no-igd", "--no-zmq", "--enable-dns-blocklist", "--prune-blockchain", "--rpc-login=$MONEROD_RPC_LOGIN"]
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux may cause issues with file watching/reading for external libraries
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: home-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: monerod
  namespace: production
  labels:
    app: monerod
spec:
  selector:
    app: monerod
  ports:
    - name: p2p
      protocol: TCP
      port: 18080
      targetPort: 18080
      nodePort: 30180
    - name: rpc
      protocol: TCP
      port: 18089
      targetPort: 18089
      nodePort: 30189
  type: NodePort