apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy
  namespace: production
data:
  server.yml: |
    base-url: "https://ntfy.$SERVICES_DOMAIN"
    cache-file: "/home/ntfy/cache.db"
    attachment-cache-dir: "/home/ntfy/attachments"
    behind-proxy: true
    auth-file: "/home/ntfy/user.db"
    auth-default-access: "deny-all"
    listen-http: ":3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: production
  labels:
    app: ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ntfy
  template:
    metadata:
      labels:
        app: ntfy
    spec:
      securityContext:
        runAsUser: $UID
        runAsGroup: $UID
        fsGroup: $UID
      containers:
        - name: ntfy
          image: binwiederhier/ntfy:latest
          imagePullPolicy: Always
          args: ["serve"]
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: /etc/ntfy
              readOnly: true
            - name: state
              mountPath: /home/ntfy
      volumes:
        - name: config
          configMap:
            name: ntfy
        - name: state
          persistentVolumeClaim:
            claimName: ntfy-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: production
  labels:
    app: ntfy
spec:
  selector:
    app: ntfy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP