apiVersion: apps/v1
kind: Deployment
metadata:
  name: send
  namespace: production
  labels:
    app: send
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send
  template:
    metadata:
      labels:
        app: send
    spec:
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
        fsGroup: $MY_UID
      containers:
        - name: send
          image: registry.gitlab.com/timvisee/send:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: state
              mountPath: /uploads
              subPath: uploads
          env:
            - name: VIRTUAL_HOST
              value: send.$SERVICES_DOMAIN
            - name: VIRTUAL_PORT
              value: "3000"
            - name: DHPARAM_GENERATION
              value: "false"
            - name: NODE_ENV
              value: production
            - name: BASE_URL
              value: https://send.$SERVICES_DOMAIN
            - name: PORT
              value: "3000"
            - name: REDIS_HOST
              value: send-db.production.svc.cluster.local
            - name: FILE_DIR
              value: /uploads
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux may cause issues with file watching/reading for external libraries
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: send-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: send
  namespace: production
  labels:
    app: send
spec:
  selector:
    app: send
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP