apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: production
  labels:
    app: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
        fsGroup: $MY_UID
      containers:
        - name: navidrome
          image: deluan/navidrome:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: media
              mountPath: /music
              subPath: Music
            - name: state
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux may cause issues with file watching/reading for external libraries
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: main-external-media-pvc
        - name: state
          persistentVolumeClaim:
            claimName: navidrome-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: production
  labels:
    app: navidrome
spec:
  selector:
    app: navidrome
  ports:
    - protocol: TCP
      port: 4533
      targetPort: 4533
  type: ClusterIP