apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: production
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`traefik.$SERVICES_DOMAIN`)
      kind: Rule
      middlewares:
        - name: forwardauth-geoblock
          namespace: production
        - name: crowdsec-bouncer
          namespace: production
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: $SERVICES_TLS_NAME-tls
