image:
  pullPolicy: Always

globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--experimental.plugins.geoblock.modulename=github.com/PascalMinder/geoblock"
  - "--experimental.plugins.geoblock.version=v0.2.8"
  - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
  - "--experimental.plugins.crowdsec-bouncer-traefik-plugin.version=v1.3.3"
deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []
  additionalVolumes:
    - name: plugins
additionalVolumeMounts:
  - name: plugins
    mountPath: /plugins-storage

logs:
  general:
    format:
    level: DEBUG
  access:
    enabled: true

ports:
  web:
    nodePort: 30080
    redirectTo:
      port: websecure
      priority: 10
    proxyProtocol:
      trustedIPs: ["$TRAEFIK_TRUSTED_IP_RANGE"] # Assuming Traefik is accessed via FRP running on the control plane node
      insecure: false
  websecure:
    nodePort: 30443
    http3:
      enabled: true
    advertisedPort: 4443
    tls:
      enabled: true
    proxyProtocol:
      trustedIPs: ["$TRAEFIK_TRUSTED_IP_RANGE"]
      insecure: false
    middlewares:
      - production-crowdsec-bouncer@kubernetescrd
      - production-forwardauth-authelia@kubernetescrd

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    allowExternalNameServices: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false
  file:
    enabled: false
    watch: false
    content: |

rbac:
  enabled: true

metrics:
  prometheus:
   service:
      enabled: true

service:
  enabled: true
  type: NodePort
  annotations: {}
  labels: {}
