apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: production
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        fsGroup: $MY_UID
      containers:
        - name: nextcloud
          image: nextcloud:latest
          ports:
            - containerPort: 80
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: nextcloud-db.production.svc.cluster.local
            - name: TRUSTED_PROXIES
              value: 10.244.0.0/16
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: nextcloud.$SERVICES_DOMAIN
            - name: OVERWRITECLIURL
              value: https://nextcloud.$SERVICES_DOMAIN
            - name: OVERWRITEPROTOCOL
              value: https
            - name: NEXTCLOUD_ADMIN_USER
              value: $NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: "$NEXTCLOUD_ADMIN_PASSWORD"
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-volume
              subPath: data
      volumes:
        - name: nextcloud-volume
          persistentVolumeClaim:
            claimName: nextcloud-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: production
  labels:
    app: nextcloud
spec:
  selector:
    app: nextcloud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
