replicaCount: 1

nextcloud:
  host: nextcloud.staging.imranr.dev
  username: imranr
  password: 2fa7660fa51eaa80d3212ae92ef3e870b6d246404eb81efabda68d5319c7d07b # PROD TODO: Replace with another random password
  containerPort: 80
  persistence:
    subPath: data

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-postgresql.production.svc.cluster.local
  user: nextcloud
  password: 2e7121445b0b8f9de5b198df477d9067e0da7fd3bc9e0aa7b5ba33e2a8bd95e9 # PROD TODO: Replace this with a different random value (and copy to postgres section below)

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: nextcloud
        password: 2e7121445b0b8f9de5b198df477d9067e0da7fd3bc9e0aa7b5ba33e2a8bd95e9
        database: nextcloud
  primary:
    persistence:
      enabled: true
      existingClaim: "nextcloud-nfs-pvc"
      subPath: "db"
    podSecurityContext:
      fsGroup: 1000
    containerSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  existingClaim: nextcloud-nfs-pvc
