apiVersion: apps/v1
kind: Deployment
metadata:
  name: isbn-lookup
  namespace: production
  labels:
    app: isbn-lookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isbn-lookup
  template:
    metadata:
      labels:
        app: isbn-lookup
    spec:
      containers:
      - name: isbn-lookup
        image: imranrdev/isbn-lookup:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ANALYTICS_SCRIPT_ELEMENT
          value: <script defer data-domain="isbn.staging.imranr.dev" src="https://plausible.staging.imranr.dev/js/script.js"></script>
---
apiVersion: v1
kind: Service
metadata:
  name: isbn-lookup
  namespace: production
  labels:
    app: isbn-lookup
spec:
  selector:
    app: isbn-lookup
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP