apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime
  namespace: production
  labels:
    app: uptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime
  template:
    metadata:
      labels:
        app: uptime
    spec:
      securityContext:
        runAsGroup: $UID
        fsGroup: $UID
      containers:
        - name: uptime
          image: louislam/uptime-kuma:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          volumeMounts:
            - name: state
              mountPath: /app/data
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: uptime-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: uptime
  namespace: production
  labels:
    app: uptime
spec:
  selector:
    app: uptime
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP