apiVersion: apps/v1
kind: Deployment
metadata:
  name: frpc
  namespace: production
  labels:
    app: frpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
    spec:
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
        fsGroup: $MY_UID
      hostNetwork: true
      containers:
        - name: frpc
          image: fatedier/frpc:v0.60.0
          volumeMounts:
            - name: config
              mountPath: /frpc.ini
              subPath: frpc.ini
      volumes:
        - name: config
          secret:
            secretName: frpc-config
            items:
              - key: frpc.ini
                path: frpc.ini
      nodeSelector:
        entrypoint: "true"
