apiVersion: apps/v1
kind: Deployment
metadata:
  name: dscpln-parsebalx
  namespace: production
  labels:
    app: dscpln-parsebalx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dscpln-parsebalx
  template:
    metadata:
      labels:
        app: dscpln-parsebalx
    spec:
      securityContext:
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: dscpln
          image: imranrdev/dscpln:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3300
          volumeMounts:
            - name: main
              mountPath: /Transactions
              subPath: Notes/Transactions
          env:
            - name: TEXTFILE_DATA_PROVIDER_DATA_PATH
              value: "/Transactions/Acc 2024.md"
            - name: MONTHLY_LIMIT_NTFY_URL
              value: https://ntfy.staging.imranr.dev/nuc_services_dscpln
            - name: WEEKLY_LIMIT_NTFY_URL
              value: https://ntfy.staging.imranr.dev/nuc_services_dscpln
            # - name: NTFY_TOKEN # PROD TODO: Add
            #   value: 
            - name: TEXTFILE_BUDGET_INIT_AMT
              value: "2400"
            - name: TEXTFILE_FIRST_WEEK_BIAS_INIT_AMT
              value: "1400"
        - name: parsebalx
          image: imranrdev/parsebalx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: main
              mountPath: /Balance
              subPath: Documents/Balance
          env:
            - name: BALANCE_PATH
              value: "/Balance/Balance.xlsx"
      volumes:
        - name: main
          persistentVolumeClaim:
            claimName: main-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dscpln-parsebalx
  namespace: production
  labels:
    app: dscpln-parsebalx
spec:
  selector:
    app: dscpln-parsebalx
  ports:
    - name: dscpln
      protocol: TCP
      port: 3300
      targetPort: 3300
    - name: parsebalx
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP