---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
  namespace: production
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/imranr/k8s/state/jellyfin
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: main-storage
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: jellyfin-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: production
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: media
              mountPath: /files
            - name: state
              mountPath: /config
              subPath: config
            - name: state
              mountPath: /cache
              subPath: cache
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: main-external-media-pvc
        - name: state
          persistentVolumeClaim:
            claimName: jellyfin-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: production
  labels:
    app: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: production
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`tv.staging.imranr.dev`)
      kind: Rule
      middlewares:
        - name: forwardauth-geoblock
          namespace: production
      services:
        - name: jellyfin
          port: 8096
  tls:
    secretName: imranr-dev-tls
