apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: production
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
        fsGroup: $MY_UID
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: media
              mountPath: /media
            - name: state
              mountPath: /config
              subPath: config
            - name: state
              mountPath: /cache
              subPath: cache
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux doesn't play well with K8s PVCs
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: main-external-media-pvc
        - name: state
          persistentVolumeClaim:
            claimName: jellyfin-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: production
  labels:
    app: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      targetPort: 8096
  type: ClusterIP