apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  namespace: production
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: $STATE_DIR/ollama
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: main-storage
              operator: In
              values:
                - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: ollama-pv
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: ollama-nfs-cm
#   namespace: production
# data:
#   etab: |
#     /data *(rw,sync,wdelay,hide,nocrossmnt,insecure,root_squash,no_all_squash,no_subtree_check,secure_locks,acl,no_pnfs,fsid=0,anonuid=65534,anongid=65534,sec=sys)
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ollama-nfs
#   namespace: production
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ollama-nfs
#   template:
#     metadata:
#       labels:
#         app: ollama-nfs
#     spec:
#       initContainers:
#         - name: nfs-modules
#           image: busybox:1.36.1-uclibc@sha256:97e3873d1f61ba651b632e4755fc52e1d90c9f6e4f01d9b720f37af5efed17e5
#           #           args:
#             - "modprobe"
#             - "nfs"
#             - "nfsd"
#           securityContext:
#             privileged: true
#             capabilities:
#               add:
#                 - "SYS_MODULE"
#           volumeMounts:
#             - mountPath: /lib/modules
#               name: modules
#               readOnly: true
#       containers:
#         - name: nfs-server
#           image: ghcr.io/trexx/docker-nfs-server:latest
#           #           ports:
#             - name: nfsv4
#               containerPort: 2049
#               protocol: TCP
#           securityContext:
#             privileged: true
#             capabilities:
#               add:
#                 - "SYS_ADMIN"
#           volumeMounts:
#             - mountPath: /data
#               name: ollama-nfs-data
#               readOnly: false
#             - name: nfs-exports
#               mountPath: /var/lib/nfs/etab
#               subPath: etab
#               readOnly: true
#       volumes:
#         - name: modules
#           hostPath:
#             path: /lib/modules
#         - name: nfs-exports
#           configMap:
#             name: ollama-nfs-cm
#         - name: ollama-nfs-data
#           persistentVolumeClaim:
#             claimName: ollama-pvc
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: ollama-nfs
#   namespace: production
# spec:
#   type: ClusterIP
#   ports:
#     - port: 2049
#   selector:
#     app: ollama-nfs
#   clusterIP: 10.96.172.227
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: ollama-nfs-pv
#   namespace: production
# spec:
#   capacity:
#     storage: 8Gi
#   accessModes:
#     - ReadWriteMany
#   nfs:
#     path: /
#     server: 10.96.172.227
#   persistentVolumeReclaimPolicy: Retain
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ollama-nfs-pvc
#   namespace: production
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 8Gi
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: ollama-nfs
#   namespace: production
# spec:
#   podSelector:
#     matchLabels:
#       app: ollama-nfs
#   policyTypes:
#   - Egress
#   - Ingress
#   egress:
#   - to:
#     - podSelector:
#         matchLabels:
#           app: ollama
#   ingress:
#   - from:
#     - podSelector:
#         matchLabels:
#           app: ollama