apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncthing
  namespace: production
  labels:
    app: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
        fsGroup: $MY_UID
      hostNetwork: true
      containers:
        - name: syncthing
          image: syncthing/syncthing:latest
          volumeMounts:
            - name: home
              mountPath: /var/syncthing
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux doesn't play well with K8s PVCs
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: home-pvc
