apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: $DOMAIN_OWNER_EMAIL
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: $DOMAIN_OWNER_EMAIL
            apiTokenSecretRef:
              name: cloudflare-token-secret
              key: cloudflare-token
