apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token-secret
  namespace: production
type: Opaque
stringData:
  cloudflare-token: bIXJXhT5QCqzEcERBl1SycTCTYijFuFQVBIvvIyC # PROD TODO: Revoke this token, generate another one, and replace it here