---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdscl
  namespace: production
  labels:
    app: mdscl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdscl
  template:
    metadata:
      labels:
        app: mdscl
    spec:
      securityContext:
        runAsUser: $MY_UID
        runAsGroup: $MY_UID
        fsGroup: $MY_UID
      containers:
        - name: mdscl-camera
          image: imranrdev/media-date-standardize-copy-loop:latest
          volumeMounts:
            - name: phonesync
              mountPath: /source
              subPath: DCIM/Camera
            - name: media
              mountPath: /destination
              subPath: Camera
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux doesn't play well with K8s PVCs
          env:
            - name: NTFY_URL
              value: "https://ntfy.$SERVICES_DOMAIN/${MAIN_NODE_HOSTNAME_LOWERCASE}_services_mdscl_errors"
            - name: NTFY_TOKEN
              value: $NTFY_SERVICE_USER_TOKEN
        - name: mdscl-screenshots
          image: imranrdev/media-date-standardize-copy-loop:latest
          volumeMounts:
            - name: phonesync
              mountPath: /source
              subPath: Screenshots
            - name: media
              mountPath: /destination
              subPath: Screenshots
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux doesn't play well with K8s PVCs
          env:
            - name: NTFY_URL
              value: "https://ntfy.$SERVICES_DOMAIN/${MAIN_NODE_HOSTNAME_LOWERCASE}_services_mdscl_errors"
            - name: NTFY_TOKEN
              value: $NTFY_SERVICE_USER_TOKEN
        - name: mdscl-screenrecs
          image: imranrdev/media-date-standardize-copy-loop:latest
          volumeMounts:
            - name: phonesync
              mountPath: /source
              subPath: "ScreenRecs"
            - name: media
              mountPath: /destination
              subPath: Screenshots
          securityContext:
            allowPrivilegeEscalation: false
            seLinuxOptions:
              type: spc_t # SELinux doesn't play well with K8s PVCs
          env:
            - name: NTFY_URL
              value: "https://ntfy.$SERVICES_DOMAIN/${MAIN_NODE_HOSTNAME_LOWERCASE}_services_mdscl_errors"
            - name: NTFY_TOKEN
              value: $NTFY_SERVICE_USER_TOKEN
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: main-media-pvc
        - name: phonesync
          persistentVolumeClaim:
            claimName: device-sync-folders-pvc